### ISSUE TITLE
Please re-upload it to GitHub Marketplace

### ISSUE THREAD

**Issue by pulimento** [dswistowski/surge-sh-action#26]
Hello,
First of all, thanks for your action.
Please, can you update it on GitHub marketplace? You have v1.0.3, but [in the market is still v1.0.1](https://github.com/marketplace/actions/publish-to-surge-sh)

Thanks in advance, have a nice day

**Comment by lafkpages** [comment]
In the marketplace it now says v.1.0.3 (yes, with a dot after the v)

**Comment by dswistowski** [comment]
released v1.1.0
