### ISSUE TITLE
difference to afc163/surge-preview?

### ISSUE THREAD

**Issue by pixelass** [dswistowski/surge-sh-action#6]
We are using afc163/surge-preview and I was wondering if this actually does the same thing. It might make sense to collaborate with the other implementation.

https://github.com/afc163/surge-preview

**Comment by dswistowski** [comment]
this action is much simpler - it just runs surge publish. 
The independent use if to deploy build project after the merge to master.

`surge-preview` project is much more complicated it's intended to create surge.sh domain for branch and teardown it when PR is closed.

I do not plan to have any more development on my action - there is no need to work to improve hammer
